[package]
name = "proto-ares"
description = "Implementación del protocolo binario Ares Galaxy (TCP/UDP packets, reader, writer)"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
bytes = { workspace = true }
byteorder = { workspace = true }
md-5 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
aes = { workspace = true }
cbc = { workspace = true }
des = { workspace = true }
sha1 = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
criterion = { version = "0.5", default-features = false }

[[bench]]
name = "packets"
harness = false
